# Generated by Django 4.1.5 on 2023-03-06 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("credit_amount", models.IntegerField()),
                ("debit_amount", models.IntegerField()),
                ("balance", models.IntegerField()),
                (
                    "id1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.register_login",
                    ),
                ),
            ],
        ),
    ]
