# Generated by Django 4.1.7 on 2023-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_transaction_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_history",
            name="id1",
            field=models.IntegerField(),
        ),
    ]
