# Generated by Django 4.1.7 on 2023-03-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_transaction_history_id1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_history",
            name="id1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.register_login"
            ),
        ),
    ]
