# Generated by Django 4.1.5 on 2023-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_transaction_history_credit_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=100)),
                ("problem", models.CharField(max_length=1000)),
            ],
        ),
    ]
