# Generated by Django 4.1.5 on 2023-03-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_login",
            name="role",
            field=models.Field(default="user"),
        ),
    ]
