# Generated by Django 4.1.5 on 2023-03-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_register_login_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register_login",
            name="role",
        ),
    ]
