# Generated by Django 4.1.5 on 2023-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_remove_register_login_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_login",
            name="role",
            field=models.CharField(default="user", editable=False, max_length=7),
        ),
    ]
