# Generated by Django 4.1.7 on 2023-03-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_rename_credit_amount_transaction_history_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction_history",
            name="timestamp",
            field=models.DateTimeField(default="2023-03-27 10:23:37.173365"),
        ),
    ]
