# Generated by Django 4.1.7 on 2023-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_alter_transaction_history_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_history",
            name="month",
            field=models.CharField(default="3", max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction_history",
            name="timestamp",
            field=models.DateTimeField(default="2023-03-30 02:27:44.142267"),
        ),
    ]
