# Generated by Django 4.1.7 on 2023-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_alter_transaction_history_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction_history",
            name="month_name",
            field=models.CharField(default="March", max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction_history",
            name="timestamp",
            field=models.DateTimeField(default="2023-03-30 02:30:34.163483"),
        ),
    ]
