# Generated by Django 4.1.7 on 2023-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_transaction_history_month_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction_history",
            name="month",
        ),
        migrations.AlterField(
            model_name="transaction_history",
            name="timestamp",
            field=models.DateTimeField(default="2023-03-30 02:31:20.482613"),
        ),
    ]
